### ISSUE TITLE
Skywars signs

### ISSUE THREAD

**Issue by PaulTDD-MC** [MysticCity/MinigamesAPI#175]
When the game sign has been created it displays as it should.
But when somebody clicks the sign, the content of that sign dissapears...

**Comment by mepeisen** [comment]
Any error in console?
Does everything work and only the text disapperas?
Which versions are you using?

**Comment by PaulTDD-MC** [comment]
I'm using version 1.14.13, spigot 1.10.2.
and no, no errors in console.

**Comment by mepeisen** [comment]
Please review MinigamesLib/Config.yml

Should contain following entries:

`
signs:
  join:
    '0': '&a<minigame>'
    '1': '&a<arena>'
    '2': '&a<count>/<maxcount>'
    '3': '&a'
  starting:
    '0': '&a<minigame>'
    '1': '&a<arena>'
    '2': '&a<count>/<maxcount>'
    '3': '&a'
  ingame:
    '0': '&4<minigame>'
    '1': '&4<arena>'
    '2': '&4<count>/<maxcount>'
    '3': '&4'
  restarting:
    '0': '&e<minigame>'
    '1': '&e<arena>'
    '2': '&e<count>/<maxcount>'
    '3': '&e'
`

**Comment by PaulTDD-MC** [comment]
I know, that's all default... And If I put SkyWars on first line and <arena> on the second line. It works, but when you click the sign to join, it just clears the sign.

**Comment by mepeisen** [comment]
Can you attach you config.yml? the whole file?

**Comment by PaulTDD-MC** [comment]
```
# The default config. Check http://dev.bukkit.org/bukkit-plugins/instances-minigamesapi/#w-tutorials 
# or https://github.com/instance01/MinigamesAPI/wiki/Default-Config-and-Item-Markup 
# for more information if you don't understand a config entry. 
# You can find classes (kits) in classes.yml, all saved arenas in arenas.yml, all messages in messages.yml. 
# You can edit/disable achievements in achievements.yml.
config:
  selection_items:
    classes_selection_item: 399
    exit_item: 152
    achievement_item: 160
    spectator_item: 345
    shop_selection_item: 388
  GUI:
    classes_gui_rows: 3
    shop_gui_rows: 3
  spectator:
    spectator_after_fall_or_death: true
    spectator_move_y_lock: true
  defaults:
    default_max_players: 4
    default_min_players: 2
    default_max_game_time_in_minutes: 30
  countdowns:
    lobby_countdown: 30
    ingame_countdown: 10
    ingame_countdown_enabled: true
    skip_lobby: false
    clearinv_while_ingamecountdown: false
  classes_enabled: true
  shop_enabled: true
  use_credits_instead_of_money_for_kits: false
  reset_inventory_when_players_leave_server: true
  color_background_wool_of_signs: false
  show_classes_without_usage_permission: true
  rewards:
    economy: true
    economy_reward: 10
    item_reward: false
    item_reward_ids: 264*1;11*1
    command_reward: false
    command: pex user <player> add SKILLZ.*
    economy_for_kills: true
    economy_reward_for_kills: 5
    command_reward_for_kills: false
    command_for_kills: pex user <player> add SKILLZ.*
    economy_for_participation: false
    economy_reward_for_participation: 5
    command_reward_for_participation: false
    command_for_participation: pex user <player> add SKILLZ.*
  stats:
    points_for_kill: 2
    points_for_win: 10
  arcade:
    enabled: true
    min_players: 1
    max_players: 16
    arena_to_prefer:
      enabled: false
      arena: arena1
    lobby_countdown: 20
    show_each_lobby_countdown: false
    infinite_mode:
      enabled: false
      seconds_to_new_round: 10
  bungee:
    game_on_join: false
    teleport_all_to_server_on_stop:
      tp: false
      server: lobby
    whitelist_while_game_running: false
  execute_cmds_on_stop: false
  cmds: ''
  cmds_after: say SERVER STOPPING;stop
  map_rotation: false
  broadcast_win: true
  buy_classes_forever: true
  disable_commands_in_arena: true
  command_whitelist: /msg,/pm,/help
  leave_command: /leave
  spawn_fireworks_for_winners: true
  powerup_spawning:
    broadcast: false
    spawn_firework: false
  use_custom_scoreboard: false
  delay:
    enabled: false
    amount_seconds: 5
  send_game_started_msg: false
  auto_add_default_kit: true
  last_man_standing_wins: true
  effects:
    blood: true
    damage_identifier_holograms: true
    dead_in_fake_bed: true
    1_8_titles: true
    1_8_spectator_mode: false
  sounds:
    lobby_countdown: none
    ingame_countdown: SUCCESSFUL_HIT
  chat_per_arena_only: false
  chat_show_score_in_arena: false
  compass_tracking_enabled: true
  allow_classes_selection_out_of_arenas: false
  send_stats_on_stop: true
  use_xp_bar_level: true
  use_old_reset_method: false
  chat_enabled: true
  extra_lobby_item:
    item0:
      enabled: false
      item: 9
      name: Custom Name
      command: say This is a custom extra lobby item.
  reset_on_leave:
    gamemode: true
    inventory: true
    xp: true
  spawn_glass_blocks: true
  version: 1
mysql:
  enabled: false
  host: 127.0.0.1
  user: root
  pw: root
  database: mcminigames
```

**Comment by mepeisen** [comment]
Two more files :-)
MinigamesLib/config.yml
MgSkyWars/messages.yml

**Comment by PaulTDD-MC** [comment]
MinigamesLib config
```
# MinigamesAPI Config #
# If you want bugfree versions, turn this to true:
# NO USE TRUE MODE!
config:
  auto_updating: true
  post_metrics: true
  party_command_enabled: true
  debug: false
  permissions_prefix: ancient.core
  permissions_kits_prefix: ancient.core.kits
  permissions_gun_prefix: ancient.core.guns
  permissions_shop_prefix: ancient.core.shopitems
  permissions_game_prefix: ancient.
  motd:
    enabled: false
    rotation: 15
    text: '<minigame> arena <arena> <state>: <players>/<maxplayers>'
    state:
      join: JOIN
      starting: STARTING
      ingame: INGAME
      restarting: RESTARTING
      disabled: DISABLED
signs_updating_time: 20
signs:
  join:
    '0': '&a<minigame>'
    '1': '&a<arena>'
    '2': '&a<count>/<maxcount>'
    '3': '&a'
  starting:
    '0': '&a<minigame>'
    '1': '&a<arena>'
    '2': '&a<count>/<maxcount>'
    '3': '&a'
  ingame:
    '0': '&4<minigame>'
    '1': '&4<arena>'
    '2': '&4<count>/<maxcount>'
    '3': '&4'
  restarting:
    '0': '&e<minigame>'
    '1': '&e<arena>'
    '2': '&e<count>/<maxcount>'
    '3': '&e'
```

MgSkyWars messages
```
# Contains all messages for easy translation. You can remove a mesage by setting it to nothing, like so: ''
signs:
  starting:
    '0': '&a[]'
    '1': '&a<arena>'
    '2': '&a<count>/<maxcount>'
    '3': '&a[]'
  join:
    '0': '&a[]'
    '1': '&a<arena>'
    '2': '&a<count>/<maxcount>'
    '3': '&a[]'
  ingame:
    '0': '&4[]'
    '1': '&4<arena>'
    '2': '&4<count>/<maxcount>'
    '3': '&4[]'
  restarting:
    '0': '&e[]'
    '1': '&e<arena>'
    '2': '&e<count>/<maxcount>'
    '3': '&e[]'
  arcade:
    '0': '[]'
    '1': '&cArcade'
    '2': <count>/<maxcount>
    '3': '[]'
  leave:
    '0': ''
    '1': '&4Leave'
    '2': ''
    '3': ''
  random:
    '0': '&a[]'
    '1': '&2Random'
    '2': ''
    '3': '&a[]'
messages:
  no_perm: '&cYou don''t have permission.'
  successfully_reloaded: '&aSuccessfully reloaded all configs.'
  successfully_set: '&aSuccessfully set &3<component>&a.'
  successfully_saved_arena: '&aSuccessfully saved &3<arena>&a.'
  arena_invalid: '&3<arena> &cappears to be invalid.'
  failed_saving_arena: '&cFailed to save &3<arena>&c.'
  broadcast_players_left: '&eThere are &4<count> &eplayers left!'
  broadcast_player_joined: '&2<player> &ajoined the arena! (<count>/<maxcount>)'
  player_died: '&c<player> died.'
  arena_action: '&aYou <action> arena &3<arena>&a!'
  you_already_are_in_arena: '&aYou already seem to be in arena &3<arena>&a!'
  you_joined_arena: '&aYou joined arena &3<arena>&a!'
  not_in_arena: '&cYou don''t seem to be in an arena right now.'
  teleporting_to_arena_in: '&7Teleporting to arena in <count>.'
  starting_in: '&aStarting in <count>!'
  failed_removing_arena: '&cFailed to remove &3<arena>&c.'
  successfully_removed: '&cSuccessfully removed &3<component>&c!'
  failed_removing_component: '&cFailed removing &3<component>&c. <cause>.'
  joined_arena: '&aYou joined &3<arena>&a.'
  you_won: '&aYou &2won &athe game!'
  you_lost: '&cYou &4lost &cthe game.'
  you_got_a_kill: '&aYou killed &2<player>!'
  player_was_killed_by: '&4<player> &cwas killed by &4<killer>&c!'
  arena_not_initialized: '&cThe arena appears to be not initialized, did you save
    the arena?'
  guns:
    attributelevel_increased: '&aThe <attribute> level was increased successfully!'
    not_enough_credits: '&cThe max level of 3 was reached or you don''t have enough
      credits. Needed: <credits>'
    too_many_main_guns: '&cYou already have 2 main guns, remove one first.'
    successfully_set_main_gun: '&aSuccessfully set a main gun (of a maximum of two).'
    all_guns: '&aYour current main guns: &2<guns>'
  arcade_next_minigame: '&6Next Arcade game: &4<minigame>&6!'
  arcade_joined_waiting: '&6You joined Arcade! Waiting for <count> more players to
    start.'
  arcade_joined_spectator: '&6You joined Arcade as a spectator! You''ll be able to
    play in the next minigame.'
  arcade_new_round: '&6Next Arcade round in <count>!'
  arena_disabled: '&cThe arena is disabled thus you can''t join.'
  you_can_leave_with: '&cYou can leave with <cmd> or /l!'
  no_perm_to_join_arena: '&cYou don''t have permission (arenas.<arena>) to join this
    arena as it''s vip!'
  set_kit: '&aSuccessfully set &2<kit>&a!'
  classes_item: '&4Classes'
  achievement_item: '&4Achievements'
  shop_item: '&4Shop'
  spectator_item: '&4Players'
  server_broadcast_winner: '&2<player> &awon the game on &2<arena>&a!'
  exit_item: '&4Leave the game'
  successfully_bought_kit: '&aSuccessfully bought &2<kit> &afor &2<money>&a.'
  scoreboard:
    title: '&4<arena>'
    lobby_title: '&4[<arena>]'
  you_got_kicked_because_vip_joined: '&cYou got kicked out of the game because a vip
    joined!'
  powerup_spawned: '&2A Powerup spawned!'
  custom_scoreboard:
    line0: Players:<playercount>
    line1: Spectators:<lostplayercount>
    line2: Alive:<playeralivecount>
    line3: Your Credits:<points>
    line4: Your Wins:<wins>
  custom_lobby_scoreboard:
    line0: Players:<playercount>
    line1: Max Players:<maxplayercount>
    line2: Your Credits:<points>
    line3: Your Wins:<wins>
  you_got_the_achievement: '&3You got the achievement &b<achievement>&3!'
  game_started: '&2The game has started!'
  author_of_the_map: '&3You are playing on the map &b<arena> &3by &b<author>&3!'
  description_of_the_map: <description>
  not_enough_money: '&cYou don''t have enough money.'
  possible_kits: '&aPossible kits: &2'
  possible_shopitems: '&aPossible shop items: &2'
  cancelled_starting: '&cThe starting countdown was cancelled because there''s only
    one player left in the arena.'
  minigame_description: ''
  successfully_bought_shopitem: '&aSuccessfully bought &2<shopitem> &afor &2<money>&a.'
  already_bought_shopitem: '&aYou already had &2<shopitem>&a.'
  you_received_rewards: '&aYou received a reward of &2<economyreward>'
  you_received_rewards_2: ' &aand '
  you_received_rewards_3: '&2<itemreward>&a!'
  already_in_arena: '&cYou are already in an arena.'
  stop_cause_maximum_game_time: '&cThe game is stopping in 5 seconds because the maximum
    game time was reached.'
  compass:
    no_player_found: '&cNo near players found!'
    found_player: '&aThe compass is tracking &3<player> &anow. Distance: <distance>'
  you_got_a_participation_reward: '&aYou received &2<economyreward> &afor participating!'
  kit_warning: '&7Be aware that you''ll only get the &8last &7kit you bought even
    if you buy all of them.'
  stats:
    line0: '&7----- &a&lStats &7-----; '
    line1: '&7Wins: &a<wins>'
    line2: '&7Loses: &c<loses>'
    line3: '&7Alltime Kills: &a<alltime_kills>'
    line4: '&7Alltime Deaths: &c<alltime_deaths>'
    line5: '&7KDR: &e<kdr>'
    line6: '&7Points: &e<points>'
    line7: ' ;&7-----------------'
  extra_life_msg: '&a<player> respawned because he used the extra life kit.'
config:
  generatedv182: true
  generatedv1102: true
```
